### ISSUE TITLE
Request for Build Unity Version

### ISSUE THREAD

**Issue by eabquina** [ruscoe/DRPG-Unity-Client#3]
Is this build for earlier than 5.0? Should I use 4.x.x? (4.7.1). 

Not sure if related, walls and floor items didn't get rendered in 5.3.1 version.. Thanks for a great sample!

**Comment by ruscoe** [comment]
You can definitely use 5.0, but the latest I tested with was only 5.0.1. I'm upgrading to 5.3.5 to see what breaks.

**Comment by eabquina** [comment]
Thanks, here is a screenshot of what it looked liked to me after build using Cloud or a Personal edition installation. Sorry, I'm not yet good with Unity yet so haven't figured out how to fix it.  I am trying now 5.0.1 and will share. 
![drpg_2](https://cloud.githubusercontent.com/assets/8427313/15492895/99fec626-21b2-11e6-9c29-541dc855b2f2.png)
![drpg_3](https://cloud.githubusercontent.com/assets/8427313/15492896/9a22c436-21b2-11e6-8639-30a0e0c7a676.png)

**Comment by eabquina** [comment]
let me know if you can access the build in these links.

-  https://build.cloud.unity3d.com/orgs/eabquina/projects/drpg-unity-client/    5.0.1

-  https://build.cloud.unity3d.com/orgs/eabquina/projects/drupal-rpg/    5.3.1

Unfortunately, same screenshot.

**Comment by ruscoe** [comment]
I wasn't able to access your builds, but I did upgrade the project using Unity 5.3.5 and got a working build. I've committed my changes if you want to try them out.

Hopefully that will work for you.

![drpg](https://cloud.githubusercontent.com/assets/87952/15528424/b3ee3832-21f8-11e6-8bf0-2662272cc886.png)

**Comment by eabquina** [comment]
I confirm that it is fixed now! I started to see the cool stuff now. Thank you.
![drpg_fix](https://cloud.githubusercontent.com/assets/8427313/15547417/4ebbe0ca-22d6-11e6-9f87-6f64567af043.png)

**Comment by ruscoe** [comment]
Outdated configuration, most likely. The project was originally built in an old version of Unity. I just let Unity upgrade the project and committed the changes it made.
